/*
 * LCD_Private.h
 *
 *  Created on: Mar 3, 2025
 *      Author: Abdalrahman
 */

#ifndef INCLUDE_HAL_LCD_LCD_PRIVATE_H_
#define INCLUDE_HAL_LCD_LCD_PRIVATE_H_

#define LCD_ROW1_BASE_ADD 127
#define LCD_ROW2_BASE_ADD 191

#define DONOT_CARE 	0

#define FUNCTION_SET 	CONC_BIT(0,0,1,1,LCD_NO_OF_LINES,LCD_CHAR_SIZE,DONOT_CARE,DONOT_CARE)
#define DISPLAY_ON_OFF_CONTROL 		CONC_BIT(0,0,0,0,1,LCD_DISPLAY_STATUS,LCD_CURSOR_DISPLAY,LCD_CURSOR_BLINK)

#define DISPLAY_CLEAR 0x01

#define ENTRY_MODE_SET CONC_BIT(0,0,0,0,0,1,LCD_DISPLAY_DIRECTION,LCD_SHIFT_ENABLE)

#endif /* INCLUDE_HAL_LCD_LCD_PRIVATE_H_ */
